version: '3.8'

services:
  postgres-test:
    image: postgres:16-alpine
    container_name: figgy-test-db
    environment:
      POSTGRES_DB: figgy_test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d figgy_test"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-test-data: